apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-tasks-api-v2-config
  namespace: backend-tasks-api-v2
  labels:
    app: backend-tasks-api-v2
data:
  LOG_LEVEL: "info"
  NODE_ENV: "production"
  ALLOWED_ORIGIN: "*"
