apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend-tasks-api-v2

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - external-secret.yaml

commonLabels:
  app.kubernetes.io/name: backend-tasks-api-v2
  app.kubernetes.io/part-of: backend-tasks-api-v2
  app.kubernetes.io/managed-by: argocd
  open-horizons/horizon: h1

images:
  - name: app-image
    newName: crsuradev.azurecr.io/backend-tasks-api-v2
    newTag: v0.1.0
